### PR TITLE
chore: Add a bot to update github actions

### PR DESCRIPTION
**Pull request by bitdivine**
# Motivation
CI is emitting warnings about outdated GitHub actions.  Updating GitHub actions is a chore, but Dependabot can reduce the workload by creating PRs to update actions.

Screenshot from 2024-02-20 13-40-45

Note: Humans still need to review the updates, so this reduces but does not remove the maintenance effort.

# Changes
- Added a Dependabot configuration to update GitHub actions periodically.

# Tests
- I use this same configuration in other repositories, and to date it has worked as expected.

### CODE REVIEW

**Review by ielashi — APPROVED** [review]

**Comment by bitdivine** [comment]
@ielashi Unfortunately both my PRs fail in CI.  It looks as if some resource is not accessible, possibly because I am making a PR from outside dfinity.

**Comment by bitdivine** [comment]
Thank you for looking, @ielashi .  I hit the update button and got the same CI error, however I note that that button creates a merge, not a rebase.  Rebased locally and hard pushed.  Waiting.. Ok, done, but the error is the same.

**Comment by bitdivine** [comment]
@ielashi I have added you to the branch repository, by the way, so that you have permission to rebase or experiment in case that is useful.

**Comment by ielashi** [comment]
@bitdivine The issue is now (finally!) fixed :)

**Pull request merged**
